/* ========================================================================
   60-day Dutch reading + writing routine for thesis preparation.
   Start: vr 15 mei 2026 — End: ma 13 juli 2026.
   ======================================================================== */

const PLAN_START_ISO = "2026-05-15"; // dag 1
const PLAN_END_ISO   = "2026-07-13"; // dag 60

const planData = [
  { day: 1,  date: "2026-05-15", dateLabel: "vr 15 mei", week: 1, theme: "AI in Hoger Onderwijs (NL)",
    read: "AI IN HOGER ONDERWIJS.pdf, p. 1-3",
    write: "Vat in je eigen woorden samen wat de auteur in de eerste pagina's beweert over AI in het onderwijs. Wat is de hoofdvraag?" },
  { day: 2,  date: "2026-05-16", dateLabel: "za 16 mei", week: 1, theme: "AI in Hoger Onderwijs (NL)",
    read: "AI IN HOGER ONDERWIJS.pdf, p. 4-6",
    write: "Beschrijf één concreet moment in je eigen opleiding waar AI je werk beïnvloed heeft — positief of negatief. Wat veranderde aan je proces?" },
  { day: 3,  date: "2026-05-17", dateLabel: "zo 17 mei", week: 1, theme: "AI in Hoger Onderwijs (NL)",
    read: "AI IN HOGER ONDERWIJS.pdf, p. 7-9",
    write: "Welke vaardigheden worden volgens jou belangrijker voor ontwerpers nu AI bestaat? En welke minder? Geef voor elk één voorbeeld." },
  { day: 4,  date: "2026-05-18", dateLabel: "ma 18 mei", week: 1, theme: "AI in Hoger Onderwijs (NL)",
    read: "AI IN HOGER ONDERWIJS.pdf, p. 10-12",
    write: "Stel: een docent verbiedt AI volledig in zijn vak. Schrijf een korte brief (≈10 zinnen) waarin je antwoordt — niet om te overtuigen, maar om je positie helder te maken." },
  { day: 5,  date: "2026-05-19", dateLabel: "di 19 mei", week: 1, theme: "AI in Hoger Onderwijs (NL)",
    read: "AI IN HOGER ONDERWIJS.pdf, p. 13-15",
    write: "Wat is voor jou het verschil tussen 'AI gebruiken om sneller te werken' en 'AI gebruiken om beter te denken'? Welke gebruik jij vaker, en waarom?" },
  { day: 6,  date: "2026-05-20", dateLabel: "wo 20 mei", week: 1, theme: "AI in Hoger Onderwijs (NL)",
    read: "AI IN HOGER ONDERWIJS.pdf, p. 16-19",
    write: "Welke zin in het hele document blijft het meeste hangen? Schrijf hem letterlijk over, en leg in 5-7 zinnen uit waarom." },

  { day: 7,  date: "2026-05-21", dateLabel: "do 21 mei", week: 2, theme: "Creativiteit & datavisualisaties (NL)",
    read: "creatvivteit data visulitaties.pdf, p. 1-4",
    write: "Wat verwacht je dat de auteur gaat zeggen over de relatie tussen creativiteit en data? Schrijf je verwachting op in 3-4 zinnen — je leest het later terug om te zien of het klopt." },
  { day: 8,  date: "2026-05-22", dateLabel: "vr 22 mei", week: 2, theme: "Creativiteit & datavisualisaties (NL)",
    read: "creatvivteit data visulitaties.pdf, p. 5-8",
    write: "Beschrijf een datavisualisatie die je recent gezien hebt (in een krant, op Instagram, in een app). Wat werkte goed, wat niet?" },
  { day: 9,  date: "2026-05-23", dateLabel: "za 23 mei", week: 2, theme: "Creativiteit & datavisualisaties (NL)",
    read: "creatvivteit data visulitaties.pdf, p. 9-12",
    write: "Kan een datavisualisatie 'mooi' zijn zonder informatief te zijn? Of omgekeerd? Neem een duidelijk standpunt in." },
  { day: 10, date: "2026-05-24", dateLabel: "zo 24 mei", week: 2, theme: "Creativiteit & datavisualisaties (NL)",
    read: "creatvivteit data visulitaties.pdf, p. 13-16",
    write: "Stel: je krijgt de opdracht om je eigen leerproces van het afgelopen semester te visualiseren. Welke vorm zou je kiezen, en waarom?" },
  { day: 11, date: "2026-05-25", dateLabel: "ma 25 mei", week: 2, theme: "Creativiteit & datavisualisaties (NL)",
    read: "creatvivteit data visulitaties.pdf, p. 17-20",
    write: "Vergelijk twee manieren waarop AI kan helpen bij datavisualisatie. Welke vind jij eerlijker tegenover de kijker, en waarom?" },
  { day: 12, date: "2026-05-26", dateLabel: "di 26 mei", week: 2, theme: "Creativiteit & datavisualisaties (NL)",
    read: "creatvivteit data visulitaties.pdf, p. 21-24",
    write: "Wat is voor jou het verschil tussen 'data tonen' en 'een verhaal vertellen met data'? Geef een voorbeeld van elk." },
  { day: 13, date: "2026-05-27", dateLabel: "wo 27 mei", week: 2, theme: "Creativiteit & datavisualisaties (NL)",
    read: "creatvivteit data visulitaties.pdf, p. 25-28",
    write: "Reflecteer: bij welk schoolproject heb je iets gevisualiseerd dat eigenlijk niet bedoeld was om gevisualiseerd te worden (een emotie, een proces, een idee)? Wat leerde je daaruit?" },
  { day: 14, date: "2026-05-28", dateLabel: "do 28 mei", week: 2, theme: "Creativiteit & datavisualisaties (NL)",
    read: "creatvivteit data visulitaties.pdf, p. 29-32",
    write: "Beschrijf in detail één pagina of figuur uit dit document dat je verraste. Waarom?" },
  { day: 15, date: "2026-05-29", dateLabel: "vr 29 mei", week: 2, theme: "Creativiteit & datavisualisaties (NL)",
    read: "creatvivteit data visulitaties.pdf, p. 33-37",
    write: "Welk woord of welke uitdrukking komt in dit document het vaakst terug? Wat zegt dat over de bedoeling van de auteur?" },
  { day: 16, date: "2026-05-30", dateLabel: "za 30 mei", week: 2, theme: "Creativiteit & datavisualisaties (NL)",
    read: "Geen nieuwe pagina's — blader terug door passages die je markeerde",
    write: "Synthese — wat zie je nu anders over creativiteit dan voor je dit las? Schrijf in 6-8 zinnen." },

  { day: 17, date: "2026-05-31", dateLabel: "zo 31 mei", week: 3, theme: "Beeldcultuur Amsterdam (NL)",
    read: "beeldcultuur amsterdam.pdf, p. 1-4",
    write: "Wat verstaat de auteur onder 'beeldcultuur'? Probeer het in je eigen woorden uit te leggen, alsof je het aan iemand uit een andere studierichting vertelt." },
  { day: 18, date: "2026-06-01", dateLabel: "ma 1 juni", week: 3, theme: "Beeldcultuur Amsterdam (NL)",
    read: "beeldcultuur amsterdam.pdf, p. 5-8",
    write: "Welke beelden zie jij het vaakst op een dag — op straat, op je telefoon, in de school? Beschrijf je 'beelddag' in 8-10 zinnen." },
  { day: 19, date: "2026-06-02", dateLabel: "di 2 juni", week: 3, theme: "Beeldcultuur Amsterdam (NL)",
    read: "beeldcultuur amsterdam.pdf, p. 9-12",
    write: "Vergelijk de beeldcultuur in Antwerpen met die in een stad die je goed kent (Istanbul, een andere stad, een dorp). Wat valt op?" },
  { day: 20, date: "2026-06-03", dateLabel: "wo 3 juni", week: 3, theme: "Beeldcultuur Amsterdam (NL)",
    read: "beeldcultuur amsterdam.pdf, p. 13-16",
    write: "Welk beeld uit je eigen leven zou je in een museum willen zien hangen, en waarom?" },
  { day: 21, date: "2026-06-04", dateLabel: "do 4 juni", week: 3, theme: "Beeldcultuur Amsterdam (NL)",
    read: "beeldcultuur amsterdam.pdf, p. 17-20",
    write: "Beschrijf één straatbeeld uit Antwerpen alsof je het aan iemand in Turkije probeert uit te leggen. Welke Nederlandse woorden heb je nodig die niet vanzelfsprekend zijn?" },
  { day: 22, date: "2026-06-05", dateLabel: "vr 5 juni", week: 3, theme: "Beeldcultuur Amsterdam (NL)",
    read: "beeldcultuur amsterdam.pdf, p. 21-24",
    write: "Wat is het verschil tussen 'een beeld bekijken' en 'een beeld lezen'? Neem één concreet voorbeeld en pas beide manieren toe." },
  { day: 23, date: "2026-06-06", dateLabel: "za 6 juni", week: 3, theme: "Beeldcultuur Amsterdam (NL)",
    read: "beeldcultuur amsterdam.pdf, p. 25-28",
    write: "Welke rol speelt AI vandaag in de beeldcultuur? Schrijf 3 observaties uit je eigen omgeving." },
  { day: 24, date: "2026-06-07", dateLabel: "zo 7 juni", week: 3, theme: "Beeldcultuur Amsterdam (NL)",
    read: "beeldcultuur amsterdam.pdf, p. 29-32",
    write: "Vat het volledige document samen in maximaal 6 zinnen, alsof het de achterflap van een boek is." },

  { day: 25, date: "2026-06-08", dateLabel: "ma 8 juni", week: 4, theme: "Reflective practice (Schön — EN lezen, NL schrijven)",
    read: "reflective practitioner - schon.pdf, p. 1-4 (EN)",
    write: "Wat verstaat Schön onder 'reflection-in-action'? Leg het uit in je eigen Nederlandse woorden, met een voorbeeld uit je eigen ontwerppraktijk." },
  { day: 26, date: "2026-06-09", dateLabel: "di 9 juni", week: 4, theme: "Reflective practice (Schön — EN lezen, NL schrijven)",
    read: "reflective practitioner - schon.pdf, p. 5-8 (EN)",
    write: "Wanneer reflecteer jij tijdens een ontwerp — vóór, tijdens, of na het maken? Beschrijf één concrete situatie waarin reflectie je werk veranderde." },
  { day: 27, date: "2026-06-10", dateLabel: "wo 10 juni", week: 4, theme: "Reflective practice (Schön — EN lezen, NL schrijven)",
    read: "Schon1992_Article_DesigningAsReflectiveConversat.pdf, p. 1-6 (EN)",
    write: "Schön schrijft over ontwerpen als een 'gesprek met materiaal'. Wat is voor jou het materiaal waarmee je het vaakst spreekt? Schrijf in 8 zinnen." },
  { day: 28, date: "2026-06-11", dateLabel: "do 11 juni", week: 4, theme: "Reflective practice (Schön — EN lezen, NL schrijven)",
    read: "Schon1992_Article_DesigningAsReflectiveConversat.pdf, p. 7-12 (EN)",
    write: "Beschrijf één moment waarin een tekening, schets of model je iets 'vertelde' dat je niet had voorzien. Hoe reageerde je erop?" },
  { day: 29, date: "2026-06-12", dateLabel: "vr 12 juni", week: 4, theme: "Reflective practice (Schön — EN lezen, NL schrijven)",
    read: "Schon1992_Article_DesigningAsReflectiveConversat.pdf, p. 13-17 (EN)",
    write: "Hoe verandert Schöns idee van 'gesprek met materiaal' wanneer dat materiaal door AI gegenereerd is? Schrijf je eerste gedachten op — dit kan een aanzet zijn voor je thesis." },

  { day: 30, date: "2026-06-13", dateLabel: "za 13 juni", week: 5, theme: "Eindsynthese eerste maand",
    read: "236-YSK.pdf (4 p.) + blader door je eigen geschreven teksten van dag 1 t.e.m. dag 29",
    write: "Wat heeft 30 dagen schrijven met je Nederlands gedaan? Wat valt je op aan je eigen tekst van dag 1 versus dag 30? Schrijf zo lang als je wil — geen woordlimiet." },

  { day: 31, date: "2026-06-14", dateLabel: "zo 14 juni", week: 6, theme: "Vlaamse praktijkstemmen",
    read: "Flanders DC: 'Minder produceren, meer cureren' — eerste deel interview (Base Design Brussel). flandersdc.be/nl/magazine/ai-grafisch-ontwerper-base-design-kpot",
    write: "Reflectie op de zin 'minder produceren, meer cureren' — past die bij jouw werkweek? Schat eerlijk in: hoeveel uur per week ben jij producent versus curator?" },
  { day: 32, date: "2026-06-15", dateLabel: "ma 15 juni", week: 6, theme: "Vlaamse praktijkstemmen",
    read: "Flanders DC — tweede deel interview, met studio kpot",
    write: "Welke uitspraak van kpot herken je in je eigen werk, en welke niet? Geef voor elk één concreet voorbeeld uit een eigen project." },
  { day: 33, date: "2026-06-16", dateLabel: "di 16 juni", week: 6, theme: "Vlaamse praktijkstemmen",
    read: "Tim Brys, 'Met AI is iedereen creatief, dus is niemand het nog' (De Standaard / AI Lab VUB) — ai.vub.ac.be/de-standaard-met-ai-is-iedereen-creatief-dus-is-niemand-het-nog/",
    write: "Brys stelt dat creativiteit door AI gedevalueerd wordt. Ga je daar in mee, of niet? Schrijf je positie in 8-10 zinnen — geen 'ja, maar' — neem een kant." },
  { day: 34, date: "2026-06-17", dateLabel: "wo 17 juni", week: 6, theme: "Vlaamse praktijkstemmen",
    read: "MediaComm, 'AI in grafisch ontwerp: hoe kunstmatige intelligentie creativiteit verandert' — mediacomm.be/ai-in-grafisch-ontwerp-hoe-kunstmatige-intelligentie/",
    write: "Vergelijk deze pragmatische blik met de filosofische blik van Brys (gisteren). Welke spreekt jou meer aan in dit moment, en waarom?" },
  { day: 35, date: "2026-06-18", dateLabel: "do 18 juni", week: 6, theme: "Synthese — Vlaamse vs. Nederlandse stem",
    read: "Geen nieuwe tekst — herlees je notities van dag 31-34",
    write: "Eerste indruk: is er een verschil tussen 'de Vlaamse stem' en 'de Nederlandse stem' over AI in design op basis van wat je tot nu las? Schrijf hypothetisch — je toetst dit later." },
  { day: 36, date: "2026-06-19", dateLabel: "vr 19 juni", week: 6, theme: "AI als ontwerpmateriaal — AIxDesign",
    read: "AIxDesign (Nadia Piet) — about-pagina en één essay op aixdesign.co",
    write: "Piet noemt AI vaak 'ontwerpmateriaal'. Wat zou JIJ AI noemen — gereedschap, partner, materiaal, gesprekspartner, of iets anders? Argumenteer je keuze in 10 zinnen." },
  { day: 37, date: "2026-06-20", dateLabel: "za 20 juni", week: 6, theme: "Eigen positie — eerste versie",
    read: "Geen leeswerk",
    write: "Schrijf in 200-300 woorden Nederlands een eerste versie van JOUW positie: wat is AI voor jou in ontwerp? Geen citaten, eigen woorden. Dit wordt later vergeleken met dag 60." },

  { day: 38, date: "2026-06-21", dateLabel: "zo 21 juni", week: 7, theme: "Academische diepte — Nicenboim (TU Delft)",
    read: "Iohanna Nicenboim, 'Designing-with AI: More-than-human Design in/through Practice' — abstract + NL stellingen. repository.tudelft.nl",
    write: "Wat verstaat Nicenboim onder 'more-than-human design'? Vertaal het concept naar je eigen woorden, met een voorbeeld uit jouw eigen praktijk." },
  { day: 39, date: "2026-06-22", dateLabel: "ma 22 juni", week: 7, theme: "Academische diepte — Nicenboim methodologie",
    read: "Nicenboim proefschrift — methodologie-hoofdstuk (browse), focus op één case study",
    write: "Welke onderzoeksmethode van Nicenboim zou je in je eigen scriptie kunnen toepassen? Beschrijf hoe je het zou aanpassen aan jouw context (grafisch ontwerp i.p.v. interactieontwerp)." },
  { day: 40, date: "2026-06-23", dateLabel: "di 23 juni", week: 7, theme: "Vocabulaire — Giaccardi 'Rethink Design'",
    read: "Elisa Giaccardi e.a., 'Rethink Design — A vocabulary for designing with AI' (TU Delft Open) — eerste 5 termen",
    write: "Kies één term uit het vocabulaire en pas hem toe op één van je eigen projecten (Zauberflöte, FREQUENTIE, of een ander). Werkt de term, of mist hij iets?" },
  { day: 41, date: "2026-06-24", dateLabel: "wo 24 juni", week: 7, theme: "Vocabulaire — Giaccardi vervolg",
    read: "Giaccardi, 'Rethink Design' — termen 6-12",
    write: "Mis je een term in dit vocabulaire die je zou willen toevoegen? Schrijf zelf een definitie van een nieuwe term — geef hem een naam, definitie, en één voorbeeld." },
  { day: 42, date: "2026-06-25", dateLabel: "do 25 juni", week: 7, theme: "AI als ontwerpmateriaal — Harbers",
    read: "Maaike Harbers, 'Verantwoord ontwerp van toepassingen met kunstmatige intelligentie' — lectorale rede (NL). Creating 010 / Hogeschool Rotterdam.",
    write: "Harbers spreekt over 'AI als ontwerpmateriaal'. Welk ander materiaal gedraagt zich het meest zoals AI — klei, water, taal, glas? Vergelijk eigenschappen in 3 punten." },
  { day: 43, date: "2026-06-26", dateLabel: "vr 26 juni", week: 7, theme: "Zachte waarden — Het Nieuwe Instituut",
    read: "'Onmetelijk belangrijk — Kunstmatige intelligentie en de zachte waarden van architectuur' (HNI / TANGRAM) — nieuweinstituut.nl/projects/onmetelijk-belangrijk",
    write: "Welke 'zachte waarden' in grafisch ontwerp kan AI niet vatten? Lijst er 5, met voor elk een uitleg van waarom AI ze mist." },
  { day: 44, date: "2026-06-27", dateLabel: "za 27 juni", week: 7, theme: "Synthese — academische week",
    read: "Herlees alle notities van week 7",
    write: "Welke academische auteur (Nicenboim, Giaccardi, Harbers, HNI) komt het dichtst bij jouw eigen scriptie-idee? Geef drie precieze redenen waarom." },

  { day: 45, date: "2026-06-28", dateLabel: "zo 28 juni", week: 8, theme: "Kritische stem — macht & Big Tech",
    read: "Marleen Stikker (Waag): 'Uiteindelijk draait het om macht' — De Creatieve Coalitie",
    write: "Stikker pleit voor publieke AI-modellen. Wat kun JIJ als beginnende ontwerper hier concreet aan doen? Bedenk drie acties op studentenschaal." },
  { day: 46, date: "2026-06-29", dateLabel: "ma 29 juni", week: 8, theme: "Praktische ethiek",
    read: "'Werken met AI — Hulpmiddel, geen vervanger' — manifest De Creatieve Coalitie",
    write: "Schrijf drie eigen regels voor JOUW omgang met AI in je werk. Formuleer ze zoals een manifest: kort, scherp, gebiedende wijs." },
  { day: 47, date: "2026-06-30", dateLabel: "di 30 juni", week: 8, theme: "Kritische tegenstem",
    read: "'Dommer dan AI' — De Groene Amsterdammer (november 2025)",
    write: "Beschrijf één moment waarin AI je 'dommer' maakte — je dacht minder na omdat AI iets voor je deed. Wat kon je achteraf wel/niet meer zelf?" },
  { day: 48, date: "2026-07-01", dateLabel: "wo 1 juli", week: 8, theme: "Empirie — Boekman #143",
    read: "Boekman #143 'Kunst en AI' — inleiding + één hoofdartikel",
    write: "Welke cijfers uit Boekman springen eruit? Schrijf de top-3 op, met voor elk een interpretatie: wat zegt dit cijfer over de positie van de maker in 2026?" },
  { day: 49, date: "2026-07-02", dateLabel: "do 2 juli", week: 8, theme: "Empirie — Boekman enquête",
    read: "Boekman-enquête onder 713 makers — focus op resultaten",
    write: "1 op 5 makers heeft minder opdrachten door GenAI. Stel je voor: jij studeert af in 2028. Hoe positioneer JIJ jezelf in deze veranderende markt? 8-10 zinnen." },
  { day: 50, date: "2026-07-03", dateLabel: "vr 3 juli", week: 8, theme: "Praktijk — Julia Janssen",
    read: "Studio Julia Janssen — kies één project en lees de Nederlandse projectomschrijving",
    write: "Wat doet Janssen anders dan een typische 'AI-kunstenaar' zoals Refik Anadol? Vergelijk visie en methode in twee korte alinea's." },
  { day: 51, date: "2026-07-04", dateLabel: "za 4 juli", week: 8, theme: "Synthese — kritische week",
    read: "Geen nieuwe tekst — herlees notities van week 8",
    write: "Schrijf een korte dialoog (½ pagina) tussen Marleen Stikker en Iohanna Nicenboim. Wat zouden zij elkaar vragen over de toekomst van AI in design?" },

  { day: 52, date: "2026-07-05", dateLabel: "zo 5 juli", week: 9, theme: "Documentaire — verborgen kosten",
    read: "VPRO Tegenlicht, 'De prijs van AI' (≈50 min)",
    write: "De documentaire toont de verborgen kost van AI: data, arbeid, energie. Hoe verandert dit jouw kijk op de tools die je dagelijks gebruikt? Wees concreet — welke tool, welk gebruik?" },
  { day: 53, date: "2026-07-06", dateLabel: "ma 6 juli", week: 9, theme: "Talk — Bas van de Poel (Modem)",
    read: "Pakhuis de Zwijger, 'Hoe kunstmatige intelligentie ons creatiever kan maken' met Bas van de Poel",
    write: "Eén concrete uitspraak van Van de Poel die je is bijgebleven + jouw eerlijke reactie. Was hij overtuigend of te enthousiast voor zijn klanten (OpenAI, Google)?" },
  { day: 54, date: "2026-07-07", dateLabel: "di 7 juli", week: 9, theme: "Podcast — filosofische blik",
    read: "De Nieuwe Wereld podcast met Ad Verbrugge en Julia Janssen (≈90 min)",
    write: "Verbrugge is filosoof, Janssen ontwerper. Welk perspectief vond je waardevoller voor JOUW scriptie? Argumenteer met twee redenen." },
  { day: 55, date: "2026-07-08", dateLabel: "wo 8 juli", week: 9, theme: "College — wat is originaliteit?",
    read: "Universiteit van Nederland, Maarten Lamers, 'Kan AI een originele hit schrijven?' (≈20 min)",
    write: "Lamers vraagt wat 'originaliteit' eigenlijk is. Geef jouw definitie van originaliteit in grafisch ontwerp anno 2026 — formuleer drie criteria." },
  { day: 56, date: "2026-07-09", dateLabel: "do 9 juli", week: 9, theme: "Boek — Rasch, Frictie (begin)",
    read: "Miriam Rasch, 'Frictie. Ethiek in tijden van dataïsme' — inleiding + hoofdstuk 1",
    write: "Rasch betoogt dat we wrijving nodig hebben. Beschrijf één recent ontwerpproces waarin wrijving je werk juist verbeterde, en één waarin gladheid het verpestte." },
  { day: 57, date: "2026-07-10", dateLabel: "vr 10 juli", week: 9, theme: "Boek — Rasch, Frictie (midden)",
    read: "Rasch, 'Frictie' — hoofdstuk 2 en 3",
    write: "Rasch koppelt dataïsme aan onthechting. Hoe kun je in een AI-workflow bewust 'tegenwicht' bouwen tegen die onthechting? Drie concrete voorstellen." },
  { day: 58, date: "2026-07-11", dateLabel: "za 11 juli", week: 9, theme: "Boek — Rasch, Frictie (slot)",
    read: "Rasch, 'Frictie' — slothoofdstuk en epiloog",
    write: "Vat 'Frictie' samen in 5 zinnen. Welke zin daarvan zou je openingsalinea van je scriptie kunnen worden?" },

  { day: 59, date: "2026-07-12", dateLabel: "zo 12 juli", week: 10, theme: "Eindsynthese — conceptmap",
    read: "Blader door alle notities van dag 31 t.e.m. dag 58. Teken op papier een conceptmap die auteurs en ideeën aan elkaar verbindt.",
    write: "Welke verbindingen tussen auteurs of ideeën ontstaan die je niet had verwacht? Beschrijf drie van die verrassende verbindingen." },
  { day: 60, date: "2026-07-13", dateLabel: "ma 13 juli", week: 10, theme: "Eindmanifest — tweede versie",
    read: "Lees je eigen tekst van dag 37 (je eerste manifest) terug.",
    write: "Schrijf nu een tweede versie van JOUW positie — 300-400 woorden Nederlands. Wat is veranderd na 30 dagen lezen? Dit is een eerste serieuze draft voor je scriptie-inleiding." },
];

// Week themes for grouping in plan view
const weekThemes = {
  1:  "AI in Hoger Onderwijs",
  2:  "Creativiteit & datavisualisaties",
  3:  "Beeldcultuur",
  4:  "Reflective practice (Schön)",
  5:  "Eindsynthese eerste maand",
  6:  "Vlaamse praktijk + AIxDesign",
  7:  "Academisch fundament",
  8:  "Kritische stemmen + ethiek",
  9:  "Podcasts/video + Rasch",
  10: "Eindmanifest",
};
